#!/bin/bash

set -e

BASE=$(dirname $0)
DATE=$(date '+%F')
TIME=$(date '+%H%M%S')

PARKRUN_DATA=${PARKRUN_DATA:-$HOME/parkrun/data}
FILE="parkrun_barcode_$DATE-$TIME.txt"

mkdir -p "${PARKRUN_DATA}/${DATE}"

echo -n "Looking for scanner..."
while [ ! -c /dev/ttyUSB0 ]
do
	sleep 1
	echo -n .
done
echo found

${BASE}/get-barcodes.py | ${BASE}/format-barcodes.pl >"${PARKRUN_DATA}/$DATE/$FILE"

echo "Done (saved to ${PARKRUN_DATA}/$DATE/$FILE)"
