#!/usr/bin/perl

# Debug mode?
#$debug = 1;

    local ($buffer, @pairs, $pair, $name, $value, %FORM);
    # Read in text
    $ENV{'REQUEST_METHOD'} =~ tr/a-z/A-Z/;
    if ($ENV{'REQUEST_METHOD'} eq "GET")
    {
	$buffer = $ENV{'QUERY_STRING'};
    }
    # Split information into name/value pairs
    @pairs = split(/&/, $buffer);
    foreach $pair (@pairs)
    {
	($name, $value) = split(/=/, $pair);
	$value =~ tr/+/ /;
	$value =~ s/%(..)/pack("C", hex($1))/eg;
	$FORM{$name} = $value;
	if ($name eq "deleteselected") {
		push @delete, $value;
		}
		
    }
    #$first_name = $FORM{first_name};




print "Content-type:text/html\r\n\r\n";
print "<html>\n";
print "<head>\n";
#print "<h2>parkrun Stopwatch / Barcode Downloader</h2>";
print "<a href=/><img src=/parkrunlogo.jpg></a>\n";
print "<br>\n";
print "<title>parkrun Stopwatch / Barcode Downloader</title>";
print "<meta name=\"viewport\" content=\"initial-scale = 1.15,maximum-scale = 3.0\" />\n";
print "</head>";
print "<body>";
print "parkrunPortable v1.3, Lawrence Billson\n";

if ($debug) {
	print "Debugging data:";
	print "Buffer is $buffer\n<br>\n";
	foreach $debugkey (sort keys %FORM) {
		print "Form key $debugkey\n";
		print "Value is $FORM{$debugkey}<br>\n";
		}

	foreach $debugkey (sort keys %ENV) {
		print "ENV key $debugkey\n";
		print "Value is $ENV{$debugkey}<br>\n";
		}


	}

if ($buffer eq "deleteall") {
	print "<hr>Deleting<hr>\n";
	`rm /www/files/*`;
	print "<a href=/><button style=\"width:200;height:24;\">Main Menu</button></a>\n";
	$menu++;
	}

if ($FORM{"deleteselected"}) {
	print "<hr>Deleting Selected Files<hr>\n";
	
	# Cycle through our list of inodes to unlink
	foreach $delfile (@delete) { 
		print "Deleted $delfile<br>\n";
		`rm /www/files/$delfile`;
		}

	print "<hr>\n";
	print "<a href=/><button style=\"width:200;height:24;\">Main Menu</button></a>\n";
	$menu++;
	}


if ($buffer eq "upgrade") {
	print "<hr>Upgrading parkrun portable<hr>\n";
	print "<hr>NOT YET IMPLEMENTED<hr>\n";
	print "<a href=/><button style=\"width:200;height:24;\">Main Menu</button></a>\n";
	$menu++;
	}

if ($buffer eq "delete") {
	print "<hr>\n";
	print "Delete the following files:<br>\n";

	print "<form action=\"/cgi-bin/parkrun\" method=\"get\">\n";
	@files = `ls /www/files`;
	foreach $file (@files) {
		$wcl = `wc -l /www/files/$file`;
		($num,$wcname) = split(' ',$wcl);
		print "     <input type=\"checkbox\" name=\"deleteselected\" value=\"$file\">$file ($num lines)<br><br>\n";
		}
	print "<hr>\n";
	#print "<input type=\"submit\" style=\"width:300;height:24;\" value=\"Delete Selected Files\"><br>\n";
	print "<a href=/cgi-bin/parkrun?deleteselected><button style=\"width:200;height:24;\">Delete Selected Files</button></a><br><br>\n";
	print "</form>\n";
	print "<br>\n";
	print "<a href=/><button style=\"width:200;height:24;\">Main Menu</button></a><br><br>\n";
	#print "<a href=/cgi-bin/parkrun?deleteall>Delete ALL files!</a>\n";
	print "<hr>\n";
	$menu++;
	}


if ($buffer eq "barcode") {
	# Confirm that we've got a USB0 but not a USB1
	$usbstat = `ls /dev/ttyUSB*`;
	if (($usbstat =~ ttyUSB0) && (!($usbstat =~ ttyUSB1))) {
		# We only have a single USB device, check that it's a pl2303
		$driver = `dmesg | grep ttyUSB0 | tail -1`;
		}

	if ($driver =~ /opticon/) {
		sleep 1;
		$status = `/www/cgi-bin/barcode.pl 2>&1`;
		print "<hr>\n";
		@status = split('\n',$status);
		foreach $bstatusline (@status) { 
			if ($bstatusline =~ /reading barcodes/) {
				print "$bstatusline";
				}
			}
		print "<hr>\n";
		}
	else {
		print "BARCODE READER NOT DETECTED, check connections or restart the parkrun portable<hr>Debug: $usbstat<hr>\n";
		print "<hr>\n";
		}
	print "<a href=/><button style=\"width:200;height:24;\">Main Menu</button></a>\n";
	if ($driver =~ /opticon/) {
		print "<hr>\n";
		print "Geek messages - $status\n";
		}


	$menu++;
	}

if ($buffer eq "barcodeclock") {
	# Confirm that we've got a USB0 but not a USB1
	$usbstat = `ls /dev/ttyUSB*`;
	if (($usbstat =~ ttyUSB0) && (!($usbstat =~ ttyUSB1))) {
		# We only have a single USB device, check that it's a pl2303
		$driver = `dmesg | grep ttyUSB0 | tail -1`;
		}

	if ($driver =~ /opticon/) {
		@status = `/www/cgi-bin/gettime.py 2>&1`;
		# Need to figure out the time
		foreach $sline (@status) {
			if ($sline =~ /OpticonTime/) {
				print "<hr>\n";
				# We've got a useful date out of it! That's pretty awesome
				print "Time from barcode scanner is $sline<br>\n";

				($junk,$dmy,$hms) = split(' ',$sline);
				($year,$month,$day) = split('-',$dmy);
				($hour,$min,$sec) = split(':',$hms);

				`date -s $year$month$day$hour$min$sec`;
				$ndate = `date`; 
				print "Time on parkrun portable is now $ndate<br>\n";
				}
#OpticonTime  2015-08-22 16:54:19
#[YYYY.]MM.DD-hh:mm[:ss]
#YYYY-MM-DD hh:mm[:ss]
#[[[[[YY]YY]MM]DD]hh]mm[.ss]


			}
		print "<hr>\n";
		#print "Status: $status\n";
		}
	else {
		print "BARCODE READER NOT DETECTED, check connections or restart the portable parkrun<hr>Debug: $usbstat<hr>\n";
		print "<hr>\n";
		}
	print "<a href=/><button style=\"width:200;height:24;\">Main Menu</button></a>\n";
	$menu++;
	}



if ($buffer eq "stopwatch") {
	# Confirm that we've got a USB0 but not a USB1
	$usbstat = `ls /dev/ttyUSB*`;
	if (($usbstat =~ ttyUSB0) && (!($usbstat =~ ttyUSB1))) {
		# We only have a single USB device, check that it's a pl2303
		$driver = `dmesg | grep ttyUSB0 | tail -1`;
		}

	if ($driver =~ /pl2303/) {
		# Run the stopwatch program in the background
		`sh -c /www/cgi-bin/bgstopwatch.sh`;
		sleep 2;
		print "<hr>Stopwatch detected OK - parkrun portable will listen out for any uploads from your stopwatch.<br>";
		print "<hr>\n";
		}
	else {
		print "<hr>\n";
		print "STOPWATCH NOT DETECTED, check connections or restart the portable parkrun<hr>Debug: $usbstat<hr>\n";
		print "<hr>\n";
		}

	print "<a href=/><button style=\"width:200;height:24;\">Main Menu</button></a>\n";
	$menu++;
	}


if ($buffer eq "sdownload") {
	$status = `/www/cgi-bin/stopwatch.pl 2>&1`;
	print "Status: $status\n";
	print "<a href=/><button style=\"width:200;height:24;\">Main Menu</button></a>\n";
	print "<hr>\n";
	$menu++;
	}

if ($buffer eq "debug") {
	print "<hr>\n";
	$dmesg = `dmesg | grep USB0`;
	print "$dmesg\n";

	foreach $vart (sort keys %ENV) {
		print "$vart = $ENV{$vart}<br>\n"
		}
	$menu++;
	}


if (!$menu) {
	print "<hr>";

	# are we in background stopwatch mode? 
	$bgps = `ps | grep bgstopwatch | grep -v grep`;
	chomp($bgps);
	if ($bgps =~ /perl/) {
		# We've got reasonable assurance that we're listening for stopwatch data
		print "Stopwatch detected, select UPLOAD ALL on the stopwatch, then check in Download Files\n";
		print "<br>\n";
		print "<hr>";
		}

	print "<a href=/cgi-bin/parkrun?barcodeclock><button style=\"width:200;height:24;\">Set Clock from Barcode Scanner</button></a>\n";
	print "<br>\n";
	print "<br>\n";
	print "<a href=/cgi-bin/parkrun?barcode><button style=\"width:200;height:24;\">Read Barcodes</button></a>\n";
	print "<br>\n";
	print "<br>\n";
	print "<a href=/cgi-bin/parkrun?stopwatch><button style=\"width:200;height:24;\">Read Stopwatch</button></a>\n";
	print "<br>\n";
	print "<br>\n";
	print "<a href=/files/><button style=\"width:200;height:24;\">Download Files</button></a>\n";
	print "<br>\n";
	print "<br>\n";
	print "<a href=/cgi-bin/parkrun?delete><button style=\"width:200;height:24;\">Delete Downloaded Data</button></a>\n";
	print "<hr>\n";
	print "<a href=/cgi-bin/parkrun?upgrade>Upgrade from USB</a>\n";
	}

print "</html>";
