#!/usr/bin/perl


    local ($buffer, @pairs, $pair, $name, $value, %FORM);
    # Read in text
    $ENV{'REQUEST_METHOD'} =~ tr/a-z/A-Z/;
    if ($ENV{'REQUEST_METHOD'} eq "GET")
    {
	$buffer = $ENV{'QUERY_STRING'};
    }
    # Split information into name/value pairs
    @pairs = split(/&/, $buffer);
    foreach $pair (@pairs)
    {
	($name, $value) = split(/=/, $pair);
	$value =~ tr/+/ /;
	$value =~ s/%(..)/pack("C", hex($1))/eg;
	$FORM{$name} = $value;
    }
    #$first_name = $FORM{first_name};




print "Content-type:text/html\r\n\r\n";
print "<html>\n";
print "<head>\n";
#print "<h2>parkrun Stopwatch / Barcode Downloader</h2>";
print "<img src=/parkrunlogo.jpg>\n";
print "<br>\n";
print "<title>parkrun Stopwatch / Barcode Downloader</title>";
print "</head>";
print "<body>";


if ($buffer eq "reallydelete") {
	print "<hr>Deleting<hr>\n";
	`rm /www/files/*`;
	print "<a href=/>Main Menu</a>\n";
	$menu++;
	}

if ($buffer eq "delete") {
	print "<hr>\n";
	print "About to delete the following files:<br>\n";
	@files = `ls -l /www/files`;
	foreach $file (@files) {
		print "$file<br>\n"
		}
	print "<hr>\n";
	print "<a href=/cgi-bin/parkrun?reallydelete>Really Delete Downloaded Files</a>\n";
	print "<br>\n";
	print "<a href=/>No! GO BACK!</a>\n";
	print "<hr>\n";
	$menu++;
	}

if ($buffer eq "barcode") {
	$status = `/www/cgi-bin/barcode.pl 2>&1`;
	print "<hr>\n";
	print "Downloading barcode\n";
	print "<hr>\n";
	print "Status: $status\n";
	print "<a href=/>Main Menu</a>\n";
	$menu++;
	}

if ($buffer eq "stopwatch") {
	print "<hr>\n";
	print "Download stopwatch NOW!\n";
	print "<hr>\n";


	$status = `/www/cgi-bin/stopwatch.pl 2>&1`;
	print "Status: $status\n";
	print "<a href=/>Main Menu</a>\n";
	print "<hr>\n";
	$menu++;
	}

if ($buffer eq "debug") {
	print "<hr>\n";
	$dmesg = `dmesg | grep USB0`;
	print "$dmesg\n";
	$menu++;
	}


if (!$menu) {
	
	print "<a href=/cgi-bin/parkrun?barcode>Read Barcodes</a>\n";
	print "<br>\n";
	print "<a href=/cgi-bin/parkrun?stopwatch>Read Stopwatch</a>\n";
	print "<br>\n";
	print "<a href=/cgi-bin/parkrun?delete>Delete Downloaded Data</a>\n";
	print "<br>\n";
	print "<a href=/files/>Download Files</a>\n";
	print "<hr>\n";
	}

print "</html>";
